name: Sparrow.metrics
comment: test global variable is cleared or not

# definition of variables shared by all the part of the inspection job
global:
  var1: 1

# definition of target this inspection will target at
target:
  fetch:
    uri: file://./test/assets/target.json

  format: json_v1

metrics:
  provider: prometheus 
  namespace: aloha
  define:
    - name: "metrics1"
      key : "haha"
      type: "counter"
      label:
        labelX: "metrics_1"
        labelZ: "metrics_4"

    - name: "metrics2"
      key : "haha2"
      type: "gauge"
      label:
        labelY: "metrics_2"

# definition of the inspection task trigger
trigger: trigger.Cron("@every 10s")

# definition of the inspection task, can be a list of tasks
task:
  - type: http
    option:
      method: GET         # GET method
      path: /index.html   # request path
      header:             # header
        user-agent: 'curl/7.52.1'
        accept: '*/*'
      body:               # if any, submit a body chunk for upload
      host: www.sina.com.cn
    check:
      condition: assert.Yes(true)
      lastly:
        - metrics.metrics1.Emit(1, nil)
        - >
          metrics.metrics2.Emit(10, {"tag1": "a"})
        - var.SetGlobal('var1', 10)
        - var.SetGlobal('var2', 20)

finally:
